@Grab('org.hsqldb:hsqldb:2.2.8')
@GrabConfig(systemClassLoader=true)

import groovy.sql.Sql

class dbAdder {

    static void main(String[] args) {
        def url = "jdbc:hsqldb:../db/company"
        def user = 'sa'
        def password = ''
        def driver = "org.hsqldb.jdbcDriver"
        def sql = Sql.newInstance(url, user, password, driver)

        sql.execute """
                CREATE TABLE IF NOT EXISTS EMPLOYEES (
                employeeId INTEGER GENERATED BY DEFAULT AS IDENTITY,
                FirstName VARCHAR(64),
                LastName VARCHAR(64),
                ContactNo VARCHAR(15),
                Email VARCHAR(255),
                City VARCHAR(64),
                State VARCHAR(64),
                Zip VARCHAR(10),
                UNIQUE(employeeId)
                );
                """
        //parse the file
        String dataPath = args[0]
        def parser = new companyXmlParser()

        parser.processCompany(dataPath) {
            List avail_data = sql.rows("SELECT * FROM EMPLOYEES WHERE FIRSTNAME = ${it.FirstName} AND LASTNAME = ${it.LastName};")
            if (avail_data.size() == 0) {
                sql.execute """ INSERT INTO EMPLOYEES (FirstName, LastName, ContactNo, Email, City, State, Zip)
                                    VALUES (${it.FirstName}, ${it.LastName}, ${it.ContactNo}, ${it.Email}, ${it.City}, ${it.State}, ${it.Zip});
                                """
            }
        }

        //check the db
        sql.eachRow("SELECT * FROM EMPLOYEES;") {row ->
            println row
        }

        sql.close()
    }
}
