@Grab('org.hsqldb:hsqldb:2.2.8')
@GrabConfig(systemClassLoader=true)

import groovy.sql.Sql

def url = "jdbc:hsqldb:../db/company"
def user = 'sa'
def password = ''
def driver = "org.hsqldb.jdbcDriver"
def sql = Sql.newInstance(url, user, password, driver)


sql.execute """
             DROP TABLE Athlete IF EXISTS cascade;
             DROP TABLE Record IF EXISTS;
             DROP TABLE EMPLOYEES IF EXISTS;
             """

sql.execute """
                CREATE TABLE EMPLOYEES (
                employeeId INTEGER GENERATED BY DEFAULT AS IDENTITY,
                FirstName VARCHAR(64),
                LastName VARCHAR(64),
                ContactNo VARCHAR(15),
                Email VARCHAR(255),
                City VARCHAR(64),
                State VARCHAR(64),
                Zip VARCHAR(10),
                UNIQUE(employeeId)
                );
                """

//add a sample entry
sql.execute(""" INSERT INTO EMPLOYEES (FirstName, LastName, ContactNo, Email, City, State, Zip)
                    VALUES ('khuyen', 'nguyen', 39428374, 'khuyen@mail.com', 'Hanoi', 'Vietnam', 10000);
                """)


//check for proper add
sql.eachRow('SELECT * FROM EMPLOYEES') {row ->
    println row
}

sql.execute(""" INSERT INTO EMPLOYEES (FirstName, LastName, ContactNo, Email, City, State, Zip)
                    VALUES ('nam', 'pham', 39428374, 'nam@mail.com', 'Hanoi', 'Vietnam', 10000);
                """)

sql.eachRow('SELECT * FROM EMPLOYEES') {row ->
    println row
}

sql.close()